// Generated by CoffeeScript 1.9.1
(function() {
  var Canvas, Image, allTheThings, argv, filenames, fs, i, inputPath, inputPath2, len, n, outputPath;

  argv = require('minimist')(process.argv.slice(2));

  Canvas = require('canvas');

  Image = Canvas.Image;

  console.log(argv);

  inputPath = argv.i != null ? argv.i : "images";

  inputPath2 = argv.j != null ? argv.j : "images2";

  outputPath = argv.o != null ? argv.o : "out";

  fs = require('fs');

  allTheThings = function(filename) {
    var canvas, ctx, image, image2, img, img2, out, stream;
    image = fs.readFileSync(__dirname + '/' + inputPath + '/' + filename);
    image2 = fs.readFileSync(__dirname + '/' + inputPath2 + '/' + filename);
    img = new Image;
    img.src = image;
    img2 = new Image;
    img2.src = image2;
    console.log("image load");
    canvas = new Canvas(1920, 1080);
    ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0);
    ctx.drawImage(img2, 0, 0);
    out = fs.createWriteStream(__dirname + '/' + outputPath + '/' + filename);
    stream = canvas.createPNGStream();
    return stream.on('data', function(chunk) {
      out.write(chunk);
      return console.log("Done writing image.");
    });
  };

  filenames = fs.readdirSync(__dirname + '/' + inputPath);

  for (i = 0, len = filenames.length; i < len; i++) {
    n = filenames[i];
    allTheThings(n);
  }

}).call(this);
