// Generated by CoffeeScript 1.9.1
(function() {
  var argv, ffmpeg, fs, getImages, inputPath, outputPath;

  ffmpeg = require('fluent-ffmpeg');

  fs = require('fs-extra');

  argv = require('minimist')(process.argv.slice(2));

  inputPath = "input.mp4";

  inputPath = argv.i != null ? argv.i : "input.mp4";

  outputPath = argv.o != null ? argv.o : "images";

  getImages = function() {
    fs.mkdirsSync(outputPath);
    console.log("Get images");
    return ffmpeg(inputPath).inputOptions('-t 16').size('1920x1080').outputOptions('-r 29.97').on('error', function(err) {
      return console.log('An error occurred: ' + err.message);
    }).on('end', function() {
      return console.log('done');
    }).on('progress', function(progress) {
      return console.log('Processing: ' + progress.timemark);
    }).save(outputPath + '/image-%3d.png');
  };

  getImages();

}).call(this);
