// Generated by CoffeeScript 1.9.1
// forked from github.com/jwill/psychic-lana
// with help from http://stackoverflow.com/questions/10906734/how-to-upload-image-into-html5-canvas
(function() {

  var imageLoader = document.querySelector('#imageLoader');
  imageLoader.addEventListener('change', handleImage, false);
  var canvas = document.querySelector('#image');
  var ctx = canvas.getContext('2d');

  function handleImage(e){
    var reader = new FileReader();
    reader.onload = function(event){
      var img = new Image();
      img.onload = function(){
          canvas.width = img.width;
          canvas.height = img.height;
          ctx.drawImage(img,0,0);
      }
      img.src = event.target.result;
    }
    reader.readAsDataURL(e.target.files[0]);     
  }

  function allTheThings(filename) {
    function makePixelInverted(r, g, b, a) {
      r = 255 - r;
      g = 255 - g;
      b = 255 - b;
      return [r, g, b, a];
    };

    function doIt() {
      var a, b, g, i, imageData, j, length, pixel, r, ref;
      imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
      length = imageData.data.length / 4;
      for (i = j = 0, ref = length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        r = imageData.data[i * 4 + 0];
        g = imageData.data[i * 4 + 1];
        b = imageData.data[i * 4 + 2];
        a = imageData.data[i * 4 + 3];
        pixel = makePixelInverted(r, g, b, a);
        imageData.data[i * 4 + 0] = pixel[0];
        imageData.data[i * 4 + 1] = pixel[1];
        imageData.data[i * 4 + 2] = pixel[2];
        imageData.data[i * 4 + 3] = pixel[3];
      }
      return ctx.putImageData(imageData, 0, 0);
    };

    doIt();
  };

  document.querySelector('#invert').onclick = function() {
    clear();
    allTheThings();
  };

}).call(this);
