// Generated by CoffeeScript 1.9.1
(function() {
  var argv, ffmpeg, fs, inputPath, outputPath, saveToVideo;

  ffmpeg = require('fluent-ffmpeg');

  fs = require('fs-extra');

  argv = require('minimist')(process.argv.slice(2));

  inputPath = argv.i != null ? argv.i : "images";

  outputPath = argv.o != null ? argv.o : "output.mp4";

  saveToVideo = function() {
    console.log("Save to video");
    return ffmpeg(inputPath + '/image-%3d.png').fps(29.97).size('1920x1080').on('error', function(err) {
      return console.log('An error occurred: ' + err.message);
    }).on('end', function() {
      return console.log('Done');
    }).save(outputPath);
  };

  saveToVideo();

}).call(this);
